# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-17 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180616_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
