# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-17 21:53
from __future__ import unicode_literals

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_review_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 17, 21, 53, 3, 854449), null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Location'),
        ),
    ]
