# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-17 21:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180617_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 17, 21, 58, 49, 794922), null=True),
        ),
    ]
